services:
    kernel.listener.symfony1_fallback:
        class: Hostnet\HnDependencyInjectionPlugin\Symfony1Fallback
        arguments: ["@kernel"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    Hostnet\HnDependencyInjectionPlugin\Symfony1Fallback:
         alias: kernel.listener.symfony1_fallback

    kernel.listener.cache_warmer:
        class: Hostnet\HnDependencyInjectionPlugin\CacheWarmer
        arguments: ["@kernel"]
        tags:
            - { name: kernel.cache_warmer }
